#!/usr/bin/env bash

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

if [[ -z $MODE ]]; then
    if uname -a|grep -i darwin  &>/dev/null; then
        MODE=mac
    else
        MODE=spaces
    fi
fi

pushd $DOTFILES
git submodule update --init \
    zsh/.oh-my-zsh/custom/themes/powerlevel10k \
    nvim/.config/nvim \
    tmux/.tmux-themepack \
    fzf \
    ohmyzsh/.oh-my-zsh \
    bbg
popd

STOW_FOLDERS=$STOW_FOLDERS MODE=$MODE DOTFILES=$DOTFILES source $DOTFILES/bbg/install
