#!/usr/bin/env bash

git submodule update --init \
    zsh/.oh-my-zsh/custom/themes/powerlevel10k \
    nvim/.config/nvim \
    tmux/.tmux-themepack \
    fzf \
    ohmyzsh/.oh-my-zsh \
    bbg

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS MODE=$MODE DOTFILES=$DOTFILES source $DOTFILES/bbg/install
