#!/bin/bash

# update and install zsh
if [[ ! $(command -v zsh) ]]; then
    echo "installing zsh"
    sudo apt-get update; sudo apt-get install zsh
    chsh -s $(which zsh)
else
    echo "zsh already installed"
fi

# change default shell
if [[ $SHELL == *"zsh"* ]]; then
    echo "setting default shell to zsh"
    chsh -s $(which zsh)
fi

# # Programs you need
# stow
# neovim
# bat
# xz
# openssl
# fd
# fzf
# gdbm
# gh
# git-delta
# grex
# md5sha1sum
# pkg-config
# pyenv
# tag
# tcl-tk
# tealdeer
# tmux
# tree
# watchman
# yarn
# docker
# jq
# direnv
# ripgrep
# readline
# pyenv
# postgresql@14

apt-get update; sudo apt-get install stow neovim fd tealdeer tree jq direnv ripgrep git-delta
powerlevel10k

echo "________________________________________
INSTALL SCRIPT: ZSH Start
"
# TODO:
# - # Set CONFIG_FILE_DIRECTORY, and add to zshrc
# - # add p10k.zsh and shit at bottom of zshrc file


if ! [ -d $HOME/.oh-my-zsh ] ; then
    echo "INSTALL SCRIPT:  ohmyzsh not installed. Retrieving and running install script"

    # Install script from https://ohmyz.sh/#install
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended
else
    echo "INSTALL SCRIPT: ohmyzsh installed"
fi

echo "
INSTALL SCRIPT: ZSH Finish
________________________________________"

./fzf/install --all

# to make file executeable run:
# chmod u+x <file_name>
# eg.
# chmod u+x install_scripts/fzf

# note: current config directory is passed to all script as arg ($1)
# Add bootstrapper functions here
# $CONFIG_DIRECTORY/install_scripts/homebrew $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/git $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/zsh $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/fzf $CONFIG_DIRECTORY
# $gitconfig CONFIG_DIRECTORY/install_scripts/tmux $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/vim $CONFIG_DIRECTORY

# $CONFIG_DIRECTORY/install_scripts/nvm $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/pyenv $CONFIG_DIRECTORY
# $CONFIG_DIRECTORY/install_scripts/node_globals $CONFIG_DIRECTORY
# $(brew --prefix)/opt/fzf/install
