#!/usr/bin/env zsh


# see install-linux for full details
# install binaries using apt get
# install fzf using install script
# install zsh, and change shell

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

source $DOTFILES/macos/utils

echo_ok "Install starting. You may be asked for your password (for sudo)."
# -----------------------------------------------------------------------------
#                               packages
# -----------------------------------------------------------------------------

if [[ -z $PACKAGES ]]; then
    # stow, neovim, bat, xz, openssl, fd, fzf, gdbm, gh, git-delta, grex,
    # md5sha1sum, pkg-config, pyenv, tag, tcl-tk, tealdeer, tmux, tree,
    # watchman, yarn, docker, jq, direnv, ripgrep, readline, pyenv,
    # postgresql@14
    PACKAGES="stow,neovim,bat,fd-find,tealdeer,tree,jq,direnv,ripgrep,git-delta,gdb"
fi


DOTFILES=$DOTFILES $DOTFILES/macOs/bootstrap

# -----------------------------------------------------------------------------
#                                stow
# -----------------------------------------------------------------------------
if [[ -z $STOW_FOLDERS ]]; then
    # ohmyzsh must be installed before zsh
    STOW_FOLDERS="bin,git,nvim,personal,tmux,ohmyzsh,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/stow


# -----------------------------------------------------------------------------
#                                  fzf
# -----------------------------------------------------------------------------

if [[ ! $(command -v fzf) ]] ; then
    ./fzf/install --all
fi

echo_ok "Bootstrapping complete"
