#!/usr/bin/env zsh

# see install-linux for full details
# install binaries using apt get
# install fzf using install script
# install zsh, and change shell

if [[ -z $STOW_FOLDERS ]]; then
    # ohmyzsh must be installed before zsh
    STOW_FOLDERS="bin,git,nvim,personal,tmux,ohmyzsh,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/stow
