#!/usr/bin/env zsh

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --no-folding -D $folder
    stow --no-folding -t $HOME $folder
done
popd

# pushd ./bbg
# ./some_executable
# popd
