#!/bin/zsh
source $DOTFILES/macos/utils

# Bootstrap script for setting up a new OSX machine
#
# This should be idempotent so it can be run multiple times.
#
# Some apps don't have a cask and so still need to be installed by hand. These
# include:
#
# - Postgres.app (http://postgresapp.com/)
#
# Notes:
#
# - If installing full Xcode, it's better to install that first from the app
#   store before running the bootstrap script. Otherwise, Homebrew can't access
#   the Xcode libraries as the agreement hasn't been accepted yet.
#
# Reading:
#
# - http://lapwinglabs.com/blog/hacker-guide-to-setting-up-your-mac
# - https://gist.github.com/MatthewMueller/e22d9840f9ea2fee4716
# - https://news.ycombinator.com/item?id=8402079
# - http://notes.jerzygangi.com/the-best-pgp-tutorial-for-mac-os-x-ever/


source $DOTFILES/macOs/core
source $DOTFILES/macOs/homebrew
source $DOTFILES/macOs/osx-settings
# source $DOTFILES/macOs/github
# source $DOTFILES/macOs/npm
# source $DOTFILES/macOs/python
# source $DOTFILES/macOs/ruby
# source $DOTFILES/macOs/vscode

