#!/usr/bin/zsh

function echo_ok() { echo -e '\033[1;32m'"$1"'\033[0m'; }
function echo_warn() { echo -e '\033[1;33m'"$1"'\033[0m'; }
function echo_error() { echo -e '\033[1;31mERROR: '"$1"'\033[0m'; }

batless() {
  bat --color=always $1|less -R
}

addToPathFront() {
  if [[ "$PATH" != *"$1"*  ]]; then
    export PATH=$1:$PATH
  fi
}

# Make and cd into directory
# https://unix.stackexchange.com/a/125386
mcd ()
{
  mkdir -p -- "$1" &&
    cd -P -- "$1"
}

# Git worktree clone. Sets up everything to get tarted in a repo
wclone(){
  # Get repo name
  url=$1
  basename=$(basename $url)
  echo $basename
  filename=${basename%.*}
  echo Cloning to file: $filename
  # extension=${basename##*.}
  # echo $extension

  # Make direcotry
  mkdir $filename
  cd $filename
  git clone $url .bare --bare
  ln -s .bare .git

  # Add some default branches to work with
  git worktree add main
  git worktree add current
  git worktree add hotfix
}

# To determine out where a process has been run from use ${PWD}
# echo "Script executed from: ${PWD}"
#
# To figure out the directory of a file that's been executed run:
BASEDIR=$(dirname $0)
# echo "Script location: ${BASEDIR}"
#
# Note: BASEDIR does not change when running a file within a file.


# Sends a notification banner to mac os
#
# Sounds can be found in:
#    /System/Library/Sounds
#    ~/Library/Sounds
#
# References:
#     https://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel
#
# Args:
#   $1:message      eg. "What email would you like to use for your global git config?"
#   $2:title        eg. "Shell Install Script"
#   $3:subtitle     eg. "git"
#   $4:sound_name?  eg. "Blow"
function mac_notification_banner()
{
    message=$1
    title=$2
    subtitle=$3
    sound_name=$4
    if [ $sound_name ]; then
        use_sound="sound name \"$sound_name\""
    fi

    script="display notification \"$message\" with title \"$title\" subtitle \"$subtitle\"$use_sound"
    osascript -e "$script"
}


# Make a sound
#
# References:
#   https://stackoverflow.com/questions/1143386/in-a-bash-script-command-how-can-i-make-a-pc-beep-noise-or-play-a-sound-file
function make_sound()
{
    echo -en "\007"
}

# Makes a sound, reads message then takes user input and returns it in the variable $user_input
#
# Args:
#     $1:message    eg. "What email your email?"
#
# Returns:
#     user_input
function get_user_input(){
    message=$1

    make_sound
    echo $message
    read user_input
}

# Checks for a file, if it exists moves it to the same location with .pre-install appended to file name
#
# Args:
#     $1:file_at    eg. "What email your email?"
#
# Returns:
#     file_path
function backup_and_move_existing_file(){
    file_path=$1
    if [[ -e $file_path || -f $file_path ]] ; then

        echo "$file_path found, moving to $file_path.pre-install"

        mv $file_path $file_path.pre-install
    fi
}

